### ISSUE TITLE
Conflicts with Terminal Debloater

### ISSUE THREAD

**Issue by sjayminsgithub** [Magisk-Modules-Repo/ViPER4Android#4]
Hi ShadySquirrel,

  Can you check for the blacklist APKs instead of their APPDIRs ?? cause I have already debloated AudioFX by Terminal Debloater, but your module still says AudioFX found..... which conflicts with the Debloater module

**Comment by ShadySquirrel** [comment]
I could, but I still need to add `.replace` to the base directory if I want everything inside of it to get replaced - placing dummy apks could create issues on some ROMs so this was easiest solution to make this cross-compatible.

But isn't Terminal debloater doing same thing as I am, just adding `.replace` dummy for Magisk to do it's magic? From their code:
```
echo "Uninstalling ${R}${app_name[${choice[$c]}]}${N}" | tr '_' ' '
mktouch $i/.replace ${app_name[${choice[$c]}]}
```

If so, it shouldn't make any issues - system is still seeing `/system/priv-app/AudioFX` folder, it's just empty.

If it IS making issues, I could add a quick test to see if it's already hidden by doing  simple`if [ -f "path/to/.replaced" ]; ` check, but this would mean that debloater should be installed before my module to prevent my module from replacing that dir...

**Comment by sjayminsgithub** [comment]
I think there's a misunderstanding, what I meant was to check if /system/*/APPDIR/APP.apk exists, which would prevent the dailogue AudioFX found, and will be no conflicts with Terminal Debloater as I too believe that using .replace is a standard for debloating via Magisk

**Comment by ShadySquirrel** [comment]
I could do that, but there is one problem: my test will fail if `APPDIR` exists, but apk name is changed and users who don't use debloaters will be left with audio effects which are in conflict.

Is this making any other (except cosmetic) issues?

**Comment by sjayminsgithub** [comment]
No issues currently, but I always fixed the cosmetic issue manually after updating, so wanted it to be automated, BTW  `[ -f "$entry/*.apk" ]`  would work in such case I think

**Comment by ShadySquirrel** [comment]
Not according to `bash`:

```
user@HOST ~ $ ls Downloads/*.apk
Downloads/2ef2c09f-37fb-4ba2-889a-865b2b4f4217.apk  Downloads/GCam5.1.018-Arnova8G2-V1.4.apk 
...
user@HOST ~ $ if [ -f "Downloads/*.apk" ]; then echo "yes!"; fi
user@HOST ~ $ 
```
And I've already had an issue [with device with non-standard? shell](https://github.com/Magisk-Modules-Repo/ViPER4Android/commit/aa27afc2cd9e507374afac4f174736b9e1191c82) so I'd avoid doing stuff like that.

**Comment by sjayminsgithub** [comment]
I understand that, but from on v3.* or 4.* , Android has mksh by default, for which it works, and regarding arrays, recoveries mostly use legacy POSIX environment, which do not support arrays, but filename generation is still performed, so It'd work, but thanks anyways

**Comment by ShadySquirrel** [comment]
Still not working with bash.

User who reported the error was installing from magisk manager, and that same code worked on my device running LOS, from both manager and recovery, but didn't on his running NitrogenOS (I think), so there are differences between implementations and possibly android versions.

Best I can do is add a small (possibly expensive check once list of blacklisted folders grows) check for apk files or simple oneliner to check if folder is already 'replaced' by other modules. If you're willing to test the other option, I'll try to make something once I'm home.

**Comment by sjayminsgithub** [comment]
I'm always available for testing, BTW, I also have a module  `MC's Charging Controller`  which don't use topjohnwu's template but my own code for installation and installed in BOOTMODE only ( due to nature of kernel hooking and template incompatibility ), and I never have gotten any issues about arrays for Magisk Manager  and also mksh is default shell on all Android versions supprted by Magisk, so why are so many developers testing their code against bash ??

**Comment by ShadySquirrel** [comment]
To my knowledge, differences are minor and scripts should be cross-system compatible; most of us tend to keep bash on our PCs because of other inner workings of OS which are hard-linked to it or simply because we're accustomed to it.

I'm always testing on my PC shell first, then on my phone, and then in manager - stuff mostly works but you can see that there are oddballs all around.

I'm keeping with module template because it makes my life easier - I just had to write two functions, instead of whole installer from scratch. "If wheel is working fine, why reinvent it?" is one thing I've learned for years I've spent in webapp development, and I tend to keep that as a rule now.

I'll drop you a message there or a zip here when I finish.
