### ISSUE TITLE
App not showing up in app drawer

### ISSUE THREAD

**Issue by Addicted5** [Magisk-Modules-Repo/ViPER4Android#5]
Hi, i'm using this module with my MI A1 & after upgrading to oreo, viper4android is not showing up in app drawer. Magisk log seems fine & can't see any error. After installing this mod even though i can't see any Viper4Android shortcut in app drawer, i see many app crashing after install. (is this some encryption related issue?)

I'm only using MI-A1-Gcam-addicted, MI-A1-Camera-Startup-Lag-Oreo module in magisk.

**Comment by ShadySquirrel** [comment]
Logs would be nice, [as per README is required](https://github.com/Magisk-Modules-Repo/ViPER4Android#issue-tracking-guidelines).

I can't tell from this perspective, but probably there is something going on with encrypted device and Magisk. I had issues with one of my devices, but other one is working flawlessly with encrypted data, so can't quite pinpoint it.

**Comment by Addicted5** [comment]
This is install log

- Copying zip to temp directory
- Installing ViPER4Android_FX_for_Magisk_v15-v6.0.1.zip
- A/B partition detected, current slot: _a
- Mounting /system, /vendor
- Device skip_initramfs detected
Archive:  /data/user/0/com.topjohnwu.magisk/cache/install.zip
  inflating: common/file_contexts_image
  inflating: common/post-fs-data.sh
  inflating: common/service.sh
  inflating: common/system.prop
  inflating: config.sh
  inflating: module.prop
*******************************
  Viper4Android Magisk module  
      by ShadySquirrel@XDA     
                               
   Based on original work by   
           topjohnwu           
*******************************
******************************
Powered by Magisk (@topjohnwu)
******************************
- Creating /data/adb/magisk_merge.img with size 64M
Creating filesystem with parameters:
    Size: 67108864
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4096
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16384
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4096 inodes and 1294/16384 blocks
- Mounting /data/adb/magisk_merge.img to /dev/tmp/magisk_img
* Module path: /dev/tmp/magisk_img/viper4android
* Temporary path: /dev/tmp/install
* APK is in /dev/tmp/install/app/ViPER4Android.apk
* Default driver is /dev/tmp/install/drivers/libv4a_fx_jb_NEON.so
* Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/install.zip
  inflating: app/ViPER4Android.apk
  inflating: drivers/libv4a_fx_jb_NEON.so
  inflating: drivers/libv4a_fx_jb_X86.so
* Checking for existing audio libs and effects
* Creating driver paths
* Copying V4A driver for arm64
* Modifying audio effects configuration
-> Found /system/etc/audio_effects.conf, copying and modifying
-> Found /system/vendor/etc/audio_effects.conf, copying and modifying
**************************************
/!\ Your device is encrypted.
/!\ You may encounter issues if app
/!\ is installed as system app
 
/!\ Please wipe device caches if you
/!\ encounter app crashes after boot.
**************************************
* Installing V4A app
 
**************************************
(i) Instalation finished.
***************************************
- Setting permissions
- Done
- All done!

**Comment by ShadySquirrel** [comment]
You may want to just upload the file here or to pastebin.
Also, magisk logs and verbose logcat are a must.
