### ISSUE TITLE
A little confusion

### ISSUE THREAD

**Issue by sjayminsgithub** [Magisk-Modules-Repo/ViPER4Android#6]
Hello @ShadySquirrel,
I noticed the movement of SEPolicy patches to service.sh from post-fs-data.sh. Seems to be done due to removal of post-fs mode from Magisk 16.4. And I fear there's a slight confusion there. The post-fs mode is dead, not the post-fs-data, which comes after post-fs. You don't need the boot scripts migration. Although that wouldn't hurt much, but the post-fs-data stage is still recommended for SEPolicy patches.
Jaymin Suthar

**Comment by ShadySquirrel** [comment]
My device didn't think so :) after upgrading to 16.4, everything using post-fs-data stopped working. I've experienced that before and rebooting usually worked, until now.

As soon as I've moved changes to service.sh, all was ok.
